---
- name: Make directories for Pathogen
  file: >
    "path={{item[0]}}"
    state=directory
  become: true
  become_user: "{{item[1]}}"
  with_nested:
    - [ '~/.vim/autoload', '~/.vim/bundle' ]
    - users


- name: Install Pathogen
  get_url: >
    url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest=~/.vim/autoload/pathogen.vim
    validate_certs=no
  become: true
  become_user: "{{item}}"
  with_items: users

- lineinfile: >
    dest=~/.vimrc
    regexp=^execute.pathogen.infect
    line="execute pathogen#infect()"
    insertbefore="{{vimrc_boundary_end_regexp}}"
  become: true
  become_user: "{{item}}"
  with_items: users

