---
- name: Make directories for Pathogen
  file: >
    "path={{item[0]}}"
    state=directory
  become: true
  become_user: "{{item[1]}}"
  with_nested:
    - [ '~/.vim/autoload', '~/.vim/bundle' ]
    - vimrc_users

- name: Install Pathogen
  get_url: >
    url=https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
    dest=~/.vim/autoload/pathogen.vim
    validate_certs=no
  become: true
  become_user: "{{item}}"
  with_items: vimrc_users

# - lineinfile: >
#     dest=~/.vimrc
#     regexp=^execute.pathogen.infect
#     line="source ~/.vim/ansible/pathogen.vim"
#     insertbefore="{{vimrc_boundary_end_regexp}}"
#   become: true
#   become_user: "{{item}}"
#   with_items: vimrc_users
 
