---
- name: Install Solarized plugin
  git: >
    repo=git://github.com/altercation/vim-colors-solarized.git 
    dest=~/.vim/bundle/vim-colors-solarized
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install Nerdtree plugin
  git: 
    repo=https://github.com/scrooloose/nerdtree.git
    dest=~/.vim/bundle/nerdtree
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"


- name: Install AutoComplPop plugin
  git: 
    repo=https://github.com/vim-scripts/AutoComplPop.git
    dest=~/.vim/bundle/AutoComplPop
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-fugitive plugin
  git:
    repo=https://github.com/tpope/vim-fugitive.git
    dest=~/.vim/bundle/vim-fugitive
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

#- name: Install CtrlP
#  git:
#    repo=https://github.com/kien/ctrlp.vim.git
#    dest=~/.vim/bundle/ctrlp.vim
#    update=yes
#    accept_hostkey=yes
#  become: true
#  become_user: "{{vim_user}}"

- name: Install rainbow_parentheses plugin
  git:
    repo=https://github.com/kien/rainbow_parentheses.vim.git
    dest=~/.vim/bundle/rainbow_parentheses
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install syntastic plugin
  git:
    repo=https://github.com/scrooloose/syntastic.git
    dest=~/.vim/bundle/syntastic
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"


- name: Install tabular plugin
  git:
    repo=https://github.com/godlygeek/tabular.git
    dest=~/.vim/bundle/tabular
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-bundler plugin
  git:
    repo=https://github.com/tpope/vim-bundler.git
    dest=~/.vim/bundle/vim-bundler
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-javascript plugin
  git:
    repo=https://github.com/pangloss/vim-javascript.git
    dest=~/.vim/bundle/vim-javascript
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-puppet plugin
  git:
    repo=https://github.com/rodjek/vim-puppet.git
    dest=~/.vim/bundle/vim-puppet
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-rails plugin
  git:
    repo=https://github.com/tpope/vim-rails.git
    dest=~/.vim/bundle/vim-rails
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install vim-sensible plugin
  git:
    repo=https://github.com/tpope/vim-sensible.git
    dest=~/.vim/bundle/vim-sensible
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install YouCompleteMe dependencies
  apt: 
    name="{{item}}"
    state=present
  with_items:
    - python-dev
    - build-essential
    - cmake

- name: Install YouCompleteMe plugin
  git:
    repo=https://github.com/Valloric/YouCompleteMe.git
    dest=~/.vim/bundle/YouCompleteMe
    update=yes
    accept_hostkey=yes
  become: true
  become_user: "{{vim_user}}"

- name: Install YouCompleteMe library
  shell: ./install.sh
    chdir=~/.vim/bundle/YouCompleteMe
  become: true
  become_user: "{{vim_user}}"

