---
- name: Make directories for Pathogen
  command: mkdir -p ~/.vim/autoload ~/.vim/bundle
  become: true
  become_user: "{{item}}"
  with_items: vimrc_users

- name: Install Pathogen
  command: >
    curl -LSso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
  become: true
  become_user: "{{item}}"
  with_items: vimrc_users

# - lineinfile: >
#     dest=~/.vimrc
#     regexp=^execute.pathogen.infect
#     line="source ~/.vim/ansible/pathogen.vim"
#     insertbefore="{{vimrc_boundary_end_regexp}}"
#   become: true
#   become_user: "{{item}}"
#   with_items: vimrc_users
 
